dom 17 ago 2025 02:31:18 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/usr/bin/chili-clonedisk b/usr/bin/chili-clonedisk
--- a/usr/bin/chili-clonedisk
+++ b/usr/bin/chili-clonedisk
@@ -10,7 +10,7 @@
 #
 #  Created: 2019/04/05
 #  Altered: 2022/10/14
-#  Updated: sáb 19 abr 2025 20:53:23 -04
+#  Updated: sáb 16 ago 2025 23:03:41 -04
 #
 #  Copyright (c) 2019-2025, Vilmar Catafesta <vcatafesta@gmail.com>
 #
@@ -34,19 +34,18 @@
 #  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #########################################################################
-#set -e
-#declare -r APP="${0##*/}"
-declare -r _APP_="chili-clonedisk"
-declare -r _VERSION_="5.4.19.20250419"
-declare -gA Alanguage=([pt_BR]=0 [en_US]=1 [de_DE]=2 [fr_FR]=3 [es_ES]=4 [it_IT]=5)
-declare -gA Alocale=([0]=pt_BR [1]=en_US [2]=de_DE [3]=fr_FR [4]=es_ES [5]=it_IT)
-readonly DEPENDENCIES=(awk cat cut dd ionice dialog grep lsblk pv sed tput which)
-dialogRcFile="$HOME/.dialogrc"
-
 #export LANGUAGE=en
 #export LANGUAGE=pt_BR
 export TEXTDOMAINDIR=/usr/share/locale
 export TEXTDOMAIN=chili-clonedisk
+
+#declare -r APP="${0##*/}"
+declare -r _APP_="chili-clonedisk"
+declare -r _VERSION_="5.8.16.20250816"
+declare -gA Alanguage=([pt_BR]=0 [en_US]=1 [de_DE]=2 [fr_FR]=3 [es_ES]=4 [it_IT]=5)
+declare -gA Alocale=([0]=pt_BR [1]=en_US [2]=de_DE [3]=fr_FR [4]=es_ES [5]=it_IT)
+readonly DEPENDENCIES=(awk cat cut dd ionice dialog grep lsblk pv sed tput which)
+dialogRcFile="$HOME/.dialogrc"
 
 # debug
 export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
@@ -310,7 +309,6 @@ alerta() {
 }
 
 #		--no-nl-expand \
-
 display_result() {
 	local xtitle="$1"
 	shift
@@ -336,18 +334,18 @@ info() {
 }
 
 debug() {
-  whiptail \
-    --fb \
-    --clear \
-    --backtitle "[debug]$0" \
-    --title "[debug]$0" \
-    --yesno "${*}\n" \
-    0 40
-  result=$?
-  if ((result)); then
-    exit
-  fi
-  return $result
+	whiptail \
+		--fb \
+		--clear \
+		--backtitle "[debug]$0" \
+		--title "[debug]$0" \
+		--yesno "${*}\n" \
+		0 40
+	result=$?
+	if ((result)); then
+		exit
+	fi
+	return $result
 }
 
 readconf() {
@@ -420,31 +418,31 @@ lastrow() { echo "$(tput lines)"; }
 lastcol() { echo "$(tput cols)"; }
 
 sh_checkdisk() {
-  local target="$1"
-  local nchoice=0
-  local dsk
-  local mnt
+	local target="$1"
+	local nchoice=0
+	local dsk
+	local mnt
 
-  # Usa df com tabulação pra evitar bugs com espaços em nomes de caminhos
-  dsk=$(df -hT | grep -F "$target")
+	# Usa df com tabulação pra evitar bugs com espaços em nomes de caminhos
+	dsk=$(df -hT | grep -F "$target")
 
-  if [[ -n "$dsk" ]]; then
-    if conf "${cwarning[$LC_DEFAULT]}" \
-"\n${BOLD}${RED}ERROR: ${cmsg_all_mounted_part[$LC_DEFAULT]}${RESET}\n\n \
+	if [[ -n "$dsk" ]]; then
+		if conf "${cwarning[$LC_DEFAULT]}" \
+			"\n${BOLD}${RED}ERROR: ${cmsg_all_mounted_part[$LC_DEFAULT]}${RESET}\n\n \
 $dsk\n\n \
 ${YELLOW}${cmsg_dismount[$LC_DEFAULT]}"; then
-      # desmontar qualquer ponto montado que contenha "$target"
-      mount | grep -F "$target" | awk '{print $3}' | while read -r mnt; do
-        if ! umount -f "$mnt" 2>/dev/null; then
-          nchoice=1
-          break
-        fi
-      done
-    else
-      nchoice=1
-    fi
-  fi
-  return $nchoice
+			# desmontar qualquer ponto montado que contenha "$target"
+			mount | grep -F "$target" | awk '{print $3}' | while read -r mnt; do
+				if ! umount -f "$mnt" 2>/dev/null; then
+					nchoice=1
+					break
+				fi
+			done
+		else
+			nchoice=1
+		fi
+	fi
+	return $nchoice
 }
 
 sh_part_info() {
@@ -508,33 +506,34 @@ replicate() {
 export -f replicate
 
 sh_time_elapsed() {
-  local end_time=$(date +%s)                # Obtém o tempo de término em segundos desde a época Unix
-  local duration=$((end_time - start_time)) # Calcula a duração em segundos
-  local hours=$((duration / 3600))
-  local minutes=$(((duration % 3600) / 60))
-  local seconds=$((duration % 60))
+	local end_time=$(date +%s)                # Obtém o tempo de término em segundos desde a época Unix
+	local duration=$((end_time - start_time)) # Calcula a duração em segundos
+	local hours=$((duration / 3600))
+	local minutes=$(((duration % 3600) / 60))
+	local seconds=$((duration % 60))
 
-  # Formatar os valores para terem sempre dois dígitos
-  hours=$(printf "%02d" $hours)
-  minutes=$(printf "%02d" $minutes)
-  seconds=$(printf "%02d" $seconds)
-  echo "$hours:$minutes:$seconds"
+	# Formatar os valores para terem sempre dois dígitos
+	hours=$(printf "%02d" $hours)
+	minutes=$(printf "%02d" $minutes)
+	seconds=$(printf "%02d" $seconds)
+	echo "$hours:$minutes:$seconds"
 }
 
 sh_start_time_elapsed() {
-  start_datetime=$(date)
-  start_time=$(date +%s)
+	start_datetime=$(date)
+	start_time=$(date +%s)
 }
 
 sh_end_time_elapsed() {
-  end_datetime=$(date)
+	end_datetime=$(date)
 }
 
 sh_clone_disk_to_image() {
 	local localtitle="${cmsg_disco_origem[$LC_DEFAULT]}"
 	local diskselected=""
 
-	sd=$(sh_list_disk "${localtitle}" "${diskselected}")
+	disk_source=$(sh_list_disk "${localtitle}" "${diskselected}")
+
 	if [[ -n "$disk_source" ]]; then
 		sh_disk_info
 		DEVICE_SOURCE="$disk_source"
@@ -552,12 +551,14 @@ sh_conf_image_name() {
 	DEVICE_SOURCE="$disk_source"
 	DEVICE_NAME="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_source]}" "$DSK_NAME")"
 	MODEL_SOURCE="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_source]}" "$DSK_MODEL")"
-	SIZE_SOURCE="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_soure]}" "$DSK_SIZE")"
+	SIZE_SOURCE="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_source]}" "$DSK_SIZE")"
 	LABEL_SOURCE="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_source]}" "$DSK_LABEL")"
 	TRAN_SOURCE="$(sh_splitarray "${AARRAY_DSK_DEVICES[$disk_source]}" "$DSK_TRAN")"
 
-  cvdisk_name="${DEVICE_SOURCE//\//_}"  # Substitui todas as barras por "_"
-  cvdisk_name="${cvdisk_name#_}.raw"    # Remove o primeiro "_" e adiciona ".raw"
+	image_format=$(sh_choose_image_format) || return 1
+
+	cvdisk_name="${DEVICE_SOURCE//\//_}"                  # Substitui todas as barras por "_"
+	cvdisk_name="${PWD}/${cvdisk_name#_}.${image_format}" # Remove o primeiro "_" e adiciona ".raw"
 	while true; do
 		exec 3>&1
 		txtDiskName=$(${DIALOG} \
@@ -569,14 +570,14 @@ sh_conf_image_name() {
 			--colors \
 			--insecure "$@" \
 			--mixedform "${cmsg_LABEL[$LC_DEFAULT]}" \
-			0 0 0 \
+			15 100 0 \
 			"Device                     : " 1 1 "$DEVICE_SOURCE" 1 28 20 0 2 \
 			"Name                       : " 2 1 "$DEVICE_NAME" 2 28 20 0 2 \
 			"Tran                       : " 3 1 "$TRAN_SOURCE" 3 28 20 0 2 \
 			"Label                      : " 4 1 "$LABEL_SOURCE" 4 28 20 0 2 \
 			"Modelo                     : " 5 1 "$MODEL_SOURCE" 5 28 20 0 2 \
 			"Tamanho                    : " 6 1 "$SIZE_SOURCE" 6 28 20 0 2 \
-			"Entre com o nome da imagem : " 7 1 "${cvdisk_name}" 7 28 40 0 0 \
+			"Entre com o nome da imagem : " 7 1 "${cvdisk_name}" 7 28 60 0 0 \
 			2>&1 1>&3)
 
 		exit_status=$?
@@ -606,42 +607,111 @@ sh_conf_image_name() {
 		esac
 		exec 3>&-
 	done
-  return 1
+	return 1
+}
+
+# função para escolher o formato da imagem
+sh_choose_image_format() {
+	local choice
+	choice=$(${DIALOG} \
+		--backtitle "$ccabec" \
+		--title "** ESCOLHA O FORMATO DE SAIDA DA IMAGEM**" \
+	  --clear \
+	  --stdout \
+	  --colors \
+		--menu "${cmsg_LABEL[$LC_DEFAULT]}\n\n\
+${BOLD}${REVERSE}${WHITE}$(gettext "Selecione o formato da imagem do device"):\
+${RESET}${BOLD}${YELLOW} ${disk_source}|${SIZE_SOURCE}|${MODEL_SOURCE}${RESET}" \
+		10 100 0 \
+		1 "RAW (.img)" \
+		2 "QCOW2 (.qcow2)")
+
+	case $choice in
+	1) echo "raw" ;;
+	2) echo "qcow2" ;;
+	*) return 1 ;;
+	esac
 }
 
 sh_make_clone_disk_to_image() {
 	local -i nchoice
+	set -o pipefail
 
 	if sh_conf_image_name; then
-    if conf "${cwarning[$LC_DEFAULT]}" \
-"${cmsg_disco_origem[LC_DEFAULT]}: ${GREEN}$DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE${RESET}\n\
-IMAGEM DESTINO : ${RED}$cvdisk_name\n\n" \
-    "${BOLD}${YELLOW}${cmsg_continuar_com_a_clonagem[$LC_DEFAULT]}?\n"; then
-      sh_start_time_elapsed
-			mensagem "${cmsg_formatando_particao[$LC_DEFAULT]}: $disk_source TO $cvdisk_name"
-			(pv -n "$disk_source" |
-        dd of=$cvdisk_name bs=4M conv=notrunc,noerror,sync) 2>&1 |
+		# escolher formato
+		#local image_format
+		#image_format=$(sh_choose_image_format) || return 1
+
+		local outfile="$cvdisk_name"
+
+		if conf "${cwarning[$LC_DEFAULT]}" \
+			"${cmsg_disco_origem[LC_DEFAULT]}: ${GREEN}$DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE${RESET}\n\
+IMAGEM DESTINO : ${RED}$outfile\n\n" \
+			"${BOLD}${YELLOW}${cmsg_continuar_com_a_clonagem[$LC_DEFAULT]}?\n"; then
+
+			sh_start_time_elapsed
+			mensagem "${cmsg_formatando_particao[$LC_DEFAULT]}: $disk_source TO $outfile"
+
+			# RAW simples com pv
+			local src_size
+			if [[ -b "$disk_source" ]]; then
+				src_size=$(sudo blockdev --getsize64 "$disk_source")
+			else
+				src_size=$(stat -c%s "$disk_source")
+			fi
+
+      SECTOR_SIZE=$(blockdev --getss $disk_source)   # setor físico (4096)
+      DISK_SIZE=$(blockdev --getsize64 $disk_source) # tamanho em bytes
+
+      (
+#       dd if="$disk_source" bs=32M          conv=notrunc,noerror,sync status=none | pv --numeric --size "$src_size" > "$outfile"
+#       dd if="$disk_source" bs=$SECTOR_SIZE conv=notrunc,noerror,sync status=none | pv --numeric --size "$src_size" > "$outfile"
+#       pv --numeric --size "$src_size" "$disk_source" | dd of="$outfile" bs=32M conv=notrunc,noerror,sync status=none
+#       pv --numeric --size "$src_size" "$disk_source" | dd of="$outfile" bs=32M conv=notrunc,noerror status=none
+			  pv --numeric --size "$src_size" "$disk_source" >"$outfile"
+      ) 2>&1 |
 				${DIALOG} \
 					--title "${cmsg_running_disk_cloning[LC_DEFAULT]^^}" \
 					--colors \
 					--gauge \
-"${BOLD}${WHITE}${REVERSE}${cmsg_running_disk_cloning[LC_DEFAULT]} (dd if=$disk_source of=$cvdisk_name bs=32M conv=notrunc,noerror,sync iflag=fullblock oflag=direct)${RESET}\n\n\
+					"${BOLD}${WHITE}${REVERSE}${cmsg_running_disk_cloning[LC_DEFAULT]} (pv → raw)${RESET}\n\n\
 ${cmsg_disco_origem[LC_DEFAULT]}: ${YELLOW}$DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE${RESET}\n\
-IMAGEM DESTINO : ${RED}$cvdisk_name" \
+IMAGEM DESTINO : ${RED}$outfile" \
 					10 100 0
-			nchoice=$?
-      sh_end_time_elapsed
-			result=$(fdisk -l "$cvdisk_name")
-			message=$(printf "\n\n%s" "$result")
-			[[ $nchoice -eq 0 ]] && display_result \
-        "fdisk -l $cvdisk_name"\
-        "${BOLD}${GREEN}${REVERSE}$(gettext "Clonagem concluída!")"\n\
-				"${RESET}${BOLD}${WHITE}$message\n\n" \
-        "Start Date time  : ${BLUE}$start_datetime${RESET}\n" \
-        "Finish Date Time : ${BLUE}$end_datetime${RESET}\n" \
-        "Time elapsed     : ${GREEN}$(sh_time_elapsed)${RESET}\n"
-			return $nchoice
 		fi
+		nchoice=$?
+
+		if [[ $image_format == "qcow2" ]]; then
+			local tmp_raw="$outfile.tmp.raw"
+			mv "$outfile" "$tmp_raw"
+
+			# Infobox estilizado enquanto converte
+			${DIALOG} --title "${cmsg_running_disk_cloning[LC_DEFAULT]^^}" --colors --infobox \
+				"\
+      ${BOLD}${WHITE}${REVERSE}Convertendo para QCOW2...${RESET}\n\n\
+      ${BOLD}Origem (RAW):${RESET} ${YELLOW}$tmp_raw${RESET}\n\
+      ${BOLD}Destino (QCOW2):${RESET} ${RED}$outfile${RESET}\n\n\
+      Aguarde, esta operação pode levar alguns minutos..." 10 70
+
+			# Conversão efetiva
+			if qemu-img convert -p -O qcow2 "$tmp_raw" "$outfile" > /dev/null ; then
+  			rm -f "$tmp_raw"
+  		fi
+		fi
+
+		sh_end_time_elapsed
+		result="$(fdisk -b $SECTOR_SIZE -l $outfile)"
+    message="$(printf "\n\n%s" "$result")"
+
+		[[ $nchoice -eq 0 ]] && display_result \
+			"fdisk -b $SECTOR_SIZE -l $outfile" \
+      "${BOLD}${GREEN}${REVERSE}Clonagem concluída!${RESET}\n\n" \
+			"${BOLD}${GREEN}${REVERSE}Info disk : $outfile${RESET}\n" \
+			"${BOLD}${WHITE}$message\n\n" \
+			"Start Date time  : ${BOLD}${BLUE}$start_datetime${RESET}\n" \
+			"Finish Date Time : ${BOLD}${BLUE}$end_datetime${RESET}\n" \
+			"Time elapsed     : ${BOLD}${GREEN}$(sh_time_elapsed)${RESET}\n"
+		return $nchoice
 	fi
 }
 
@@ -731,7 +801,7 @@ sh_list_partition() {
 	local part_selected="$2"
 
 	while true; do
-    sh_part_info
+		sh_part_info
 		local array=()
 		local i
 		local n=0
@@ -823,8 +893,8 @@ sh_choose_source_disk() {
 }
 
 sh_choose_target_disk() {
-  local localtitle="${cmsg_disco_destino[$LC_DEFAULT]}"
-  local disk_selected="$disk_source"
+	local localtitle="${cmsg_disco_destino[$LC_DEFAULT]}"
+	local disk_selected="$disk_source"
 
 	disk_target=$(sh_list_disk "${localtitle}" "${disk_selected}")
 	if [ "$disk_source" == "$disk_target" ]; then
@@ -842,8 +912,8 @@ sh_choose_target_disk() {
 		if [[ "$(sh_toBytes "$SIZE_SOURCE")" -gt "$(sh_toBytes "$SIZE_TARGET")" ]]; then
 			if ! conf "${YELLOW}${cwarning[$LC_DEFAULT]}" \
 				"\n${BOLD}${RED}${REVERSE}$(gettext "O disco de DESTINO é menor que o disco de ORIGEM")${RESET}\n\n" \
-        "${BOLD}${WHITE}${cmsg_disco_origem[LC_DEFAULT]} : $DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE\n" \
-        "${BOLD}${WHITE}${cmsg_disco_destino[LC_DEFAULT]}: $DEVICE_TARGET | $SIZE_TARGET | $MODEL_TARGET${RESET}\n\n" \
+				"${BOLD}${WHITE}${cmsg_disco_origem[LC_DEFAULT]} : $DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE\n" \
+				"${BOLD}${WHITE}${cmsg_disco_destino[LC_DEFAULT]}: $DEVICE_TARGET | $SIZE_TARGET | $MODEL_TARGET${RESET}\n\n" \
 				"${YELLOW}$(gettext "Prosseguir?")"; then
 				init
 			fi
@@ -851,11 +921,11 @@ sh_choose_target_disk() {
 
 		sh_backup_partitions "$disk_target" "$NAME_TARGET"
 		if ! sh_checkdisk "$disk_target"; then
-      alerta "CHOOSEDISK" "${cmsg_nec_dismount[LC_DEFAULT]}"
+			alerta "CHOOSEDISK" "${cmsg_nec_dismount[LC_DEFAULT]}"
 			die "ERRO: ${cmsg_nec_dismount[LC_DEFAULT]}"
 		fi
 		sh_confclone "$disk_source" "$disk_target"
-    sh_reset_conf
+		sh_reset_conf
 	fi
 }
 
@@ -881,7 +951,7 @@ sh_choose_target_partition() {
 	part_target=$(sh_list_partition "${localtitle}" "${part_selected}")
 	if [ "$part_source" == "$part_target" ]; then
 		alerta "${cwarning[$LC_DEFAULT]}" "\n   \Z1${cmsg_disco_identico[$LC_DEFAULT]} \n\n      \Z4SOURCE DISK : \Z1\Zr$MODEL_SOURCE\ZR\n \Z4DISK TARGET : \Z1\Zr$MODEL_TARGET\ZR"
-    sh_choose_target_partition
+		sh_choose_target_partition
 	fi
 
 	if [[ -n "$part_target" ]]; then
@@ -894,8 +964,8 @@ sh_choose_target_partition() {
 		if [[ "$(sh_toBytes "$SIZE_SOURCE")" -gt "$(sh_toBytes "$SIZE_TARGET")" ]]; then
 			if ! conf "${YELLOW}${cwarning[$LC_DEFAULT]}" \
 				"\n${BOLD}${RED}${REVERSE}$(gettext "O disco de DESTINO é menor que o disco de ORIGEM")${RESET}\n\n" \
-        "${BOLD}${WHITE}${cmsg_part_origem[LC_DEFAULT]} : $DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE ${RESET} \n" \
-        "${BOLD}${WHITE}${cmsg_part_destino[LC_DEFAULT]}: $DEVICE_TARGET | $SIZE_TARGET | $MODEL_TARGET ${RESET} \n\n" \
+				"${BOLD}${WHITE}${cmsg_part_origem[LC_DEFAULT]} : $DEVICE_SOURCE | $SIZE_SOURCE | $MODEL_SOURCE ${RESET} \n" \
+				"${BOLD}${WHITE}${cmsg_part_destino[LC_DEFAULT]}: $DEVICE_TARGET | $SIZE_TARGET | $MODEL_TARGET ${RESET} \n\n" \
 				"${YELLOW}$(gettext "Prosseguir?")"; then
 				init
 			fi
@@ -906,15 +976,15 @@ sh_choose_target_partition() {
 			die "ERRO: ${cmsg_nec_dismount[LC_DEFAULT]}"
 		fi
 		sh_confclone "$part_source" "$part_target"
-    sh_reset_conf
+		sh_reset_conf
 	fi
 }
 
 sh_reset_conf() {
-  disk_source=
-  disk_target=
-  part_source=
-  part_target=
+	disk_source=
+	disk_target=
+	part_source=
+	part_target=
 }
 
 sh_backup_partitions() {
@@ -938,8 +1008,8 @@ sh_backup_partitions() {
 }
 
 sh_confclone() {
-  local source="$1"
-  local target="$2"
+	local source="$1"
+	local target="$2"
 
 	if conf "${cwarning[$LC_DEFAULT]}" \
 		"\n${cmsg_todos_os_dados_serao_perdidos[$LC_DEFAULT]}\n\n""\
@@ -953,8 +1023,8 @@ ${BLUE} ${cmsg_disco_origem[LC_DEFAULT]}:  $DEVICE_SOURCE | $SIZE_SOURCE | $MODE
 }
 
 sh_domakeclone() {
-  local source="$1"
-  local target="$2"
+	local source="$1"
+	local target="$2"
 	local -i nchoice
 
 	mensagem "${cmsg_formatando_particao[$LC_DEFAULT]}: $source TO $target"
@@ -980,8 +1050,8 @@ ${cmsg_disco_destino[LC_DEFAULT]}: ${RED}$DEVICE_TARGET | $SIZE_TARGET | $MODEL_
 sh_Language() {
 	cmsg_nec_dismount[pt_BR]=$(gettext "Necessário desmontar a partição antes de reparticionar")
 	cwarning[pt_BR]=$(gettext "** AVISO **")
-  cmsg_all_mounted_part[pt_BR]=$(gettext "Necessário desmontar as partições abaixo antes de prosseguir")
-  cmsg_dismount[pt_BR]=$(gettext "Desmontar ?")
+	cmsg_all_mounted_part[pt_BR]=$(gettext "Necessário desmontar as partições abaixo antes de prosseguir")
+	cmsg_dismount[pt_BR]=$(gettext "Desmontar ?")
 	cmsg_Error[pt_BR]=$(gettext "ERRO")
 	cmsg_info_disco[pt_BR]=$(gettext "Info disco")
 	cmsg_Ok[pt_BR]=$(gettext "Ok")
@@ -1079,29 +1149,29 @@ sh_checkrootOLD() {
 }
 
 sh_checkroot() {
-  if [[ "$(id -u)" != "0" ]]; then
-    elevate_to_root "$@"
-  fi
-  ccabec+=' [root]'
+	if [[ "$(id -u)" != "0" ]]; then
+		elevate_to_root "$@"
+	fi
+	ccabec+=' [root]'
 }
 
 log_err() {
-  printf " %b %s\\n" "${CROSS}" "${*}"
+	printf " %b %s\\n" "${CROSS}" "${*}"
 }
 
 elevate_to_root() {
-  log_err "This script must be run as root. Elevating privileges..."
+	log_err "This script must be run as root. Elevating privileges..."
 
-  # Tenta usar sudo primeiro (caso esteja configurado)
-  if command -v sudo >/dev/null 2>&1; then
-    exec sudo bash "$0" "$@"
-  fi
+	# Tenta usar sudo primeiro (caso esteja configurado)
+	if command -v sudo >/dev/null 2>&1; then
+		exec sudo bash "$0" "$@"
+	fi
 
-  # Se sudo falhar, tenta su
-  if command -v su >/dev/null 2>&1; then
-    exec su -c "$0 $*"
-  fi
-  die "Error: Unable to elevate privileges. Run manually as root."
+	# Se sudo falhar, tenta su
+	if command -v su >/dev/null 2>&1; then
+		exec su -c "$0 $*"
+	fi
+	die "Error: Unable to elevate privileges. Run manually as root."
 }
 
 DOT() {
@@ -1179,8 +1249,8 @@ sh_choose_clone_type() {
 				--menu "${cmsg_LABEL[$LC_DEFAULT]}\n\n${YELLOW}$(gettext "Escolha o tipo de clone"):${RESET}" \
 				10 80 0 \
 				0 "$(gettext "Clonar Disco para Disco")" \
-				1 "$(gettext "Clonar Partição para Partição")" \
-				2 "$(gettext "Clonar Disco para Imagem")" \
+				1 "$(gettext "Clonar Disco para Imagem")" \
+				2 "$(gettext "Clonar Partição para Partição")" \
 				3 "$(gettext "Clonar Imagem Disco para Partição")" \
 				4 "$(gettext "Gravar ISO para Disco")" \
 				5 "$(gettext "Listar Discos")"
@@ -1194,8 +1264,8 @@ sh_choose_clone_type() {
 		esac
 		case $clone_type in
 		0) sh_choose_source_disk ;;
-		1) sh_choose_source_partition "ORIGEM" ;;
-		2) sh_clone_disk_to_image ;;
+		1) sh_clone_disk_to_image ;;
+		2) sh_choose_source_partition "ORIGEM" ;;
 		4) sh_execute_iso2usb ;;
 		5) sh_list_disk ;;
 		esac
@@ -1234,5 +1304,6 @@ done
 sh_checkroot "$@"
 sh_checkDependencies "${DEPENDENCIES[*]}"
 #init "$@"
+
 sh_choose_clone_type
 sh_choose_source_disk
